// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ef04_TobbATobbKapcsolat;

namespace ef04_TobbATobbKapcsolat.Migrations
{
    [DbContext(typeof(IskolaContext))]
    [Migration("20220127115319_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ef04_TobbATobbKapcsolat.Tanulo", b =>
                {
                    b.Property<int>("tanuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("szuletesiDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tanuloNev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("tanuloId");

                    b.ToTable("Tanulok");
                });

            modelBuilder.Entity("ef04_TobbATobbKapcsolat.Teszt", b =>
                {
                    b.Property<int>("tesztId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tesztMegnevezes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("tesztId");

                    b.ToTable("Teszt");
                });

            modelBuilder.Entity("ef04_TobbATobbKapcsolat.TesztEredmenyek", b =>
                {
                    b.Property<int>("tanuloId")
                        .HasColumnType("int");

                    b.Property<int>("tesztId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("eredmeny")
                        .HasColumnType("int");

                    b.HasKey("tanuloId", "tesztId");

                    b.HasIndex("tesztId");

                    b.ToTable("tesztEredmenyek");
                });

            modelBuilder.Entity("ef04_TobbATobbKapcsolat.TesztEredmenyek", b =>
                {
                    b.HasOne("ef04_TobbATobbKapcsolat.Tanulo", "Tanulo")
                        .WithMany("Teszteredmenyek")
                        .HasForeignKey("tanuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ef04_TobbATobbKapcsolat.Teszt", "Teszt")
                        .WithMany("Teszteredmenyek")
                        .HasForeignKey("tesztId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tanulo");

                    b.Navigation("Teszt");
                });

            modelBuilder.Entity("ef04_TobbATobbKapcsolat.Tanulo", b =>
                {
                    b.Navigation("Teszteredmenyek");
                });

            modelBuilder.Entity("ef04_TobbATobbKapcsolat.Teszt", b =>
                {
                    b.Navigation("Teszteredmenyek");
                });
#pragma warning restore 612, 618
        }
    }
}
